export type ModerationView =
  | "dashboard"
  | "reports"
  | "content"
  | "logs"
  | "analytics"
  | "discord-bot"
  | "users"
  | "subscriptions"
  | "roles"
  | "automation"
  | "announcements"
  | "settings"
  | "appeals"
  | "messaging"
  | "notifications"
  | "feedback"
  | "support-tickets"
  | "developer";

